export const GET_TASK_REQUEST = "GET_TASK_REQUEST"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"
export const GET_TASK_FAILURE = "GET_TASK_FAILURE" 

export const POST_TASK_REQUEST = "POST_TASK_REQUEST"
export const POST_TASK_SUCCESS = "POST_TASK_SUCCESS"
export const POST_TASK_FAILURE = "POST_TASK_FAILURE"

export const PATCH_TASK_REQUEST = "PATCH_TASK_REQUEST"
export const PATCH_TASK_SUCCESS = "PATCH_TASK_SUCCESS"
export const PATCH_TASK_FAILURE = "PATCH_TASK_FAILURE"